### ISSUE TITLE
license.license_text should support labels

### ISSUE THREAD

**Issue by junglegoog** [bazelbuild/rules_license#68]
https://github.com/bazelbuild/rules_license/blob/main/rules/license.bzl#L112 prevents specifying license texts that are labels.

My project (Fuchsia) needs label support for:
1. To take advantage of "select(...)", which is needed when licenses are different under certain build conditions.
2. Some of our licenses reside outside of the Bazel package folder and can't be glob. That is because Fuchsia assembles system out of prebuilts from other repositories and the tools used to fetch these prebuilts + licenses (e.g. Jiri or git repo) typically do that into a separate place from the Bazel rules that wrap them.

To solve, once can implement the above check at the rule itself, instead of in the macro. e.g.
```
 if not ctx.file.license_text.is_source:
        fail("License file ", ctx.file.license_text.path, "must be a source file, not generated")
```

**Comment by carpenterjc** [comment]
Another case I encounter is where you need to extract the license from a file. For example sqlite `https://www.sqlite.org/index.html` where the license text is the preamble of `sqlite3.h` so you need to add a rule to process that file to extract the license text.

**Comment by aiuto** [comment]
I am not in favor of supporting select() on any attribute of license.
The license text IS the license text. It should not be selectable. In fact, when we make it possible for rules to be in a "no configuration"  config we'll make license that way.

If different uses have different licenses, that could be done with multiple license() targets, and having the library select the right one in parallel with the selects that get the right target specific dependencies.

That leaves the question of assembling license text from targets in another repository and pointing to them by label. 
That may be a reasonable idea, but it is not on my priority list. For now, I would suggest that you vendor in rules_license and make custom modifications to it. That is always the suggested route anyway so that organizations can inject their own compliance policies into the system.

**Comment by aiuto** [comment]
I think I found a middle ground I can live with.
- Modify `license` so that it does not enforce single file with `glob`
- Make it easy for someone who vendors in the rules to add back in the enforcement.
  I will admit that this is mostly to make keeping Google and github in sync easier. But since I do development on both sides, any velocity improvements there are worthwhile.
- I'm still not in favor of a select on any of the attributes. My future plan is to mark them as non-configurable if we can ever get that into starlark.
