### ISSUE TITLE
Allow rulesets to adopt rules_license 

### ISSUE THREAD

**Issue by fmeum** [bazelbuild/rules_license#9]
While trying out `rules_license` for a ruleset I maintain, I noticed three problems that made it difficult for me to use:

1. The well-known `license_kind`s are not publicly visible (fixed by #7).
2. It is not possible to set the `visibility` of `license` targets (fixed by #8).
3. ~~There is no release, so the repository can't be safely loaded via `http_archive`.~~ This turned out to be an "urban legend", see https://github.com/bazel-contrib/SIG-rules-authors/issues/11#issuecomment-982676431.

Is `rules_license` considered to be in a stable enough state that rulesets could already use it to add `applicable_licenses` with well-known `license_kinds`  to their public targets? If so, it would be great if these three problems could be resolved.

**Comment by fmeum** [comment]
@aiuto Friendly ping.

**Comment by aiuto** [comment]
I am starting to work on this now. Stay tuned. And maybe read https://docs.google.com/document/d/1XszGbpMYNHk_FGRxKJ9IXW10KxMPdQpF5wWbZFpA4C8/edit#

**Comment by aiuto** [comment]
Believed fixed.  We are using this from rules_pkg, and within Bazel itself.
It's still a very slim feature set. I'm using Bazel as a test case to wind through a lot of issues related to adding license attestation to rules that don't have it.  That is higher priority for me than adding features, because the features don't do much good if you have no license attestations to drive them.
